services:
  next:
    container_name: mercari-next
    build:
      context: ./next
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./next:/app
      - node_modules:/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"

  fastapi:
    container_name: mercari-fastapi
    build:
      context: ./fastapi
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./fastapi/app:/app

  db: #ユーザ名：root, パスワード：なし
    container_name: mercari-db
    build:
      context: ./mysql
      dockerfile: Dockerfile.dev
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: "mercari"
      TZ: "Asia/Tokyo"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    container_name: mercari-dbconsole
    image: phpmyadmin:latest
    ports:
      - "8081:80"
  
volumes:
  node_modules:
  mysql_data: